#include <omdetect/internal/preamble.h>

/* Enforce resolving OMD_PLATFORM_NAME here. */
#if defined(OMD_PLATFORM_NAME)
#undef OMD_PLATFORM_NAME
#endif

#if OMD_PLATFORM == OMD_PLATFORM_AIX
    #define OMD_PLATFORM_NAME OMD_PLATFORM_AIX_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_AMDAHL_UTS
    #define OMD_PLATFORM_NAME OMD_PLATFORM_AMDAHL_UTS_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_AMIGA
    #define OMD_PLATFORM_NAME OMD_PLATFORM_AMIGA_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_ANDROID
    #define OMD_PLATFORM_NAME OMD_PLATFORM_ANDROID_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_APOLLO_AEGIS
    #define OMD_PLATFORM_NAME OMD_PLATFORM_APOLLO_AEGIS_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_APOLLO_DOMAIN_OS
    #define OMD_PLATFORM_NAME OMD_PLATFORM_APOLLO_DOMAIN_OS_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_AROS
    #define OMD_PLATFORM_NAME OMD_PLATFORM_AROS_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_BEOS
    #define OMD_PLATFORM_NAME OMD_PLATFORM_BEOS_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_BLUE_GENE_L
    #define OMD_PLATFORM_NAME OMD_PLATFORM_BLUE_GENE_L_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_BLUE_GENE_P
    #define OMD_PLATFORM_NAME OMD_PLATFORM_BLUE_GENE_P_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_BLUE_GENE_Q
    #define OMD_PLATFORM_NAME OMD_PLATFORM_BLUE_GENE_Q_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_BSD
    #define OMD_PLATFORM_NAME OMD_PLATFORM_BSD_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_BSDI
    #define OMD_PLATFORM_NAME OMD_PLATFORM_BSDI_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_CONVEX
    #define OMD_PLATFORM_NAME OMD_PLATFORM_CONVEX_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_CPM
    #define OMD_PLATFORM_NAME OMD_PLATFORM_CPM_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_CYGWIN
    #define OMD_PLATFORM_NAME OMD_PLATFORM_CYGWIN_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_DC_OSX
    #define OMD_PLATFORM_NAME OMD_PLATFORM_DC_OSX_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_DG_UX
    #define OMD_PLATFORM_NAME OMD_PLATFORM_DG_UX_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_DRAGONFLY
    #define OMD_PLATFORM_NAME OMD_PLATFORM_DRAGONFLY_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_DYNIX_PTX
    #define OMD_PLATFORM_NAME OMD_PLATFORM_DYNIX_PTX_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_ECOS
    #define OMD_PLATFORM_NAME OMD_PLATFORM_ECOS_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_EMSCRIPTEN
    #define OMD_PLATFORM_NAME OMD_PLATFORM_EMSCRIPTEN_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_EMX
    #define OMD_PLATFORM_NAME OMD_PLATFORM_EMX_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_FREEBSD
    #define OMD_PLATFORM_NAME OMD_PLATFORM_FREEBSD_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_FUCHSIA
    #define OMD_PLATFORM_NAME OMD_PLATFORM_FUCHSIA_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_GNU_HURD
    #define OMD_PLATFORM_NAME OMD_PLATFORM_GNU_HURD_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_HAIKU
    #define OMD_PLATFORM_NAME OMD_PLATFORM_HAIKU_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_HI_UX_MPP
    #define OMD_PLATFORM_NAME OMD_PLATFORM_HI_UX_MPP_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_HP_UX
    #define OMD_PLATFORM_NAME OMD_PLATFORM_HP_UX_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_ILLUMOS
    #define OMD_PLATFORM_NAME OMD_PLATFORM_ILLUMOS_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_INTEGRITY
    #define OMD_PLATFORM_NAME OMD_PLATFORM_INTEGRITY_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_INTERIX
    #define OMD_PLATFORM_NAME OMD_PLATFORM_INTERIX_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_IOS
    #define OMD_PLATFORM_NAME OMD_PLATFORM_IOS_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_IOS_SIMULATOR
    #define OMD_PLATFORM_NAME OMD_PLATFORM_IOS_SIMULATOR_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_IRIX
    #define OMD_PLATFORM_NAME OMD_PLATFORM_IRIX_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_LINUX
    #define OMD_PLATFORM_NAME OMD_PLATFORM_LINUX_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_LYNX
    #define OMD_PLATFORM_NAME OMD_PLATFORM_LYNX_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_MACOS
    #define OMD_PLATFORM_NAME OMD_PLATFORM_MACOS_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_MINIX
    #define OMD_PLATFORM_NAME OMD_PLATFORM_MINIX_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_MINT
    #define OMD_PLATFORM_NAME OMD_PLATFORM_MINT_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_MORPHOS
    #define OMD_PLATFORM_NAME OMD_PLATFORM_MORPHOS_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_MPE_IX
    #define OMD_PLATFORM_NAME OMD_PLATFORM_MPE_IX_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_MSDOS
    #define OMD_PLATFORM_NAME OMD_PLATFORM_MSDOS_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_MSX
    #define OMD_PLATFORM_NAME OMD_PLATFORM_MSX_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_NACL
    #define OMD_PLATFORM_NAME OMD_PLATFORM_NACL_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_NETBSD
    #define OMD_PLATFORM_NAME OMD_PLATFORM_NETBSD_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_NEXTSTEP
    #define OMD_PLATFORM_NAME OMD_PLATFORM_NEXTSTEP_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_NONSTOP
    #define OMD_PLATFORM_NAME OMD_PLATFORM_NONSTOP_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_NUCLEUS_RTOS
    #define OMD_PLATFORM_NAME OMD_PLATFORM_NUCLEUS_RTOS_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_OPENBSD
    #define OMD_PLATFORM_NAME OMD_PLATFORM_OPENBSD_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_OPENSERVER
    #define OMD_PLATFORM_NAME OMD_PLATFORM_OPENSERVER_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_OS2
    #define OMD_PLATFORM_NAME OMD_PLATFORM_OS2_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_OS400
    #define OMD_PLATFORM_NAME OMD_PLATFORM_OS400_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_OS9
    #define OMD_PLATFORM_NAME OMD_PLATFORM_OS9_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_PALMOS
    #define OMD_PLATFORM_NAME OMD_PLATFORM_PALMOS_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_PLAN9
    #define OMD_PLATFORM_NAME OMD_PLATFORM_PLAN9_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_QNX
    #define OMD_PLATFORM_NAME OMD_PLATFORM_QNX_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_REACTOS
    #define OMD_PLATFORM_NAME OMD_PLATFORM_REACTOS_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_SERENITY
    #define OMD_PLATFORM_NAME OMD_PLATFORM_SERENITY_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_SOLARIS
    #define OMD_PLATFORM_NAME OMD_PLATFORM_SOLARIS_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_SINUX
    #define OMD_PLATFORM_NAME OMD_PLATFORM_SINUX_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_STRATUS_VOS
    #define OMD_PLATFORM_NAME OMD_PLATFORM_STRATUS_VOS_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_SUNOS
    #define OMD_PLATFORM_NAME OMD_PLATFORM_SUNOS_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_SYLLABLE
    #define OMD_PLATFORM_NAME OMD_PLATFORM_SYLLABLE_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_SYMBIAN
    #define OMD_PLATFORM_NAME OMD_PLATFORM_SYMBIAN_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_TRU64
    #define OMD_PLATFORM_NAME OMD_PLATFORM_TRU64_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_ULTRIX
    #define OMD_PLATFORM_NAME OMD_PLATFORM_ULTRIX_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_UNICOS
    #define OMD_PLATFORM_NAME OMD_PLATFORM_UNICOS_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_UNICOS_MP
    #define OMD_PLATFORM_NAME OMD_PLATFORM_UNICOS_MP_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_UNIX
    #define OMD_PLATFORM_NAME OMD_PLATFORM_UNIX_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_UNIXWARE
    #define OMD_PLATFORM_NAME OMD_PLATFORM_UNIXWARE_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_UWIN
    #define OMD_PLATFORM_NAME OMD_PLATFORM_UWIN_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_VMS
    #define OMD_PLATFORM_NAME OMD_PLATFORM_VMS_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_VXWORKS
    #define OMD_PLATFORM_NAME OMD_PLATFORM_VXWORKS_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_WINDOWS
    #define OMD_PLATFORM_NAME OMD_PLATFORM_WINDOWS_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_WINDOWS_CE
    #define OMD_PLATFORM_NAME OMD_PLATFORM_WINDOWS_CE_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_WINDU
    #define OMD_PLATFORM_NAME OMD_PLATFORM_WINDU_CE_NAME
#elif OMD_PLATFORM == OMD_PLATFORM_ZOS
    #define OMD_PLATFORM_NAME OMD_PLATFORM_ZOS_NAME
#endif

/* Safeguard */
#if !defined(OMD_PLATFORM_NAME)
    #define OMD_PLATFORM_NAME OMD_PLATFORM_UNKNOWN_NAME
#endif
