#include <omdetect/internal/preamble.h>

/* Enforce resolving OMD_STD_*_NAME here. */
#if defined(OMD_STD_C_NAME)
    #undef OMD_STD_C_NAME
#endif
#if defined(OMD_STD_CPP_NAME)
    #undef OMD_STD_CPP_NAME
#endif
#if defined(OMD_STD_POSIX_NAME)
    #undef OMD_STD_POSIX_NAME
#endif
#if defined(OMD_STD_XOPEN_NAME)
    #undef OMD_STD_XOPEN_NAME
#endif

/* OMD_STD_C_NAME */
#if OMD_STD_C_VERSION >= OMD_STD_C23
    #define OMD_STD_C_NAME OMD_STD_C23_NAME
#elif OMD_STD_C_VERSION >= OMD_STD_C17
    #define OMD_STD_C_NAME OMD_STD_C17_NAME
#elif OMD_STD_C_VERSION >= OMD_STD_C11
    #define OMD_STD_C_NAME OMD_STD_C11_NAME
#elif OMD_STD_C_VERSION >= OMD_STD_C99
    #define OMD_STD_C_NAME OMD_STD_C99_NAME
#elif OMD_STD_C_VERSION >= OMD_STD_C94
    #define OMD_STD_C_NAME OMD_STD_C94_NAME
#elif OMD_STD_C_VERSION >= OMD_STD_C90
    #define OMD_STD_C_NAME OMD_STD_C90_NAME
#elif OMD_STD_C_VERSION >= OMD_STD_C89
    #define OMD_STD_C_NAME OMD_STD_C89_NAME
#endif

/* OMD_STD_CPP_NAME */
#if OMD_STD_CPP_VERSION >= OMD_STD_CPP23
    #define OMD_STD_CPP_NAME OMD_STD_CPP23_NAME
#elif OMD_STD_CPP_VERSION >= OMD_STD_CPP20
    #define OMD_STD_CPP_NAME OMD_STD_CPP20_NAME
#elif OMD_STD_CPP_VERSION >= OMD_STD_CPP17
    #define OMD_STD_CPP_NAME OMD_STD_CPP17_NAME
#elif OMD_STD_CPP_VERSION >= OMD_STD_CPP14
    #define OMD_STD_CPP_NAME OMD_STD_CPP14_NAME
#elif OMD_STD_CPP_VERSION >= OMD_STD_CPP11
    #define OMD_STD_CPP_NAME OMD_STD_CPP11_NAME
#elif OMD_STD_CPP_VERSION >= OMD_STD_CPP98
    #define OMD_STD_CPP_NAME OMD_STD_CPP98_NAME
#endif

/* OMD_STD_POSIX_NAME */
#if OMD_STD_POSIX_VERSION >= OMD_STD_POSIX_1_2008
    #define OMD_STD_POSIX_NAME OMD_STD_POSIX_1_2008_NAME
#elif OMD_STD_POSIX_VERSION >= OMD_STD_POSIX_1_2001
    #define OMD_STD_POSIX_NAME OMD_STD_POSIX_1_2001_NAME
#elif OMD_STD_POSIX_VERSION >= OMD_STD_POSIX_1C_1995
    #define OMD_STD_POSIX_NAME OMD_STD_POSIX_1C_1995_NAME
#elif OMD_STD_POSIX_VERSION >= OMD_STD_POSIX_1B_1993
    #define OMD_STD_POSIX_NAME OMD_STD_POSIX_1B_1993_NAME
#elif OMD_STD_POSIX_VERSION >= OMD_STD_POSIX_1_1990
    #define OMD_STD_POSIX_NAME OMD_STD_POSIX_1_1990_NAME
#elif OMD_STD_POSIX_VERSION >= OMD_STD_POSIX_1_1988
    #define OMD_STD_POSIX_NAME OMD_STD_POSIX_1_1988_NAME
#endif

/* OMD_STD_XOPEN_NAME */
#if OMD_STD_XOPEN_VERSION >= OMD_STD_XOPEN_SUS4
    #define OMD_STD_XOPEN_NAME OMD_STD_XOPEN_SUS4_NAME
#elif OMD_STD_XOPEN_VERSION >= OMD_STD_XOPEN_SUS3
    #define OMD_STD_XOPEN_NAME OMD_STD_XOPEN_SUS3_NAME
#elif OMD_STD_XOPEN_VERSION >= OMD_STD_XOPEN_SUS2
    #define OMD_STD_XOPEN_NAME OMD_STD_XOPEN_SUS2_NAME
#elif OMD_STD_XOPEN_VERSION >= OMD_STD_XOPEN_SUS1
    #define OMD_STD_XOPEN_NAME OMD_STD_XOPEN_SUS1_NAME
#elif OMD_STD_XOPEN_VERSION >= OMD_STD_XOPEN_XPG4
    #define OMD_STD_XOPEN_NAME OMD_STD_XOPEN_XPG4_NAME
#elif OMD_STD_XOPEN_VERSION >= OMD_STD_XOPEN_XPG3
    #define OMD_STD_XOPEN_NAME OMD_STD_XOPEN_XPG3_NAME
#endif

/* Safegaurds */
#if !defined(OMD_STD_C_NAME)
    #define OMD_STD_C_NAME OMD_STD_NONE_NAME
#endif
#if !defined(OMD_STD_CPP_NAME)
    #define OMD_STD_CPP_NAME OMD_STD_NONE_NAME
#endif
#if !defined(OMD_STD_POSIX_NAME)
    #define OMD_STD_POSIX_NAME OMD_STD_NONE_NAME
#endif
#if !defined(OMD_STD_XOPEN_NAME)
    #define OMD_STD_XOPEN_NAME OMD_STD_NONE_NAME
#endif
