#include <omdetect/internal/preamble.h>

/* Enforce resolving OMD_CC_NAME here. */
#if defined(OMD_CC_NAME)
#undef OMD_CC_NAME
#endif

#if OMD_CC == OMD_CC_ACC
    #define OMD_CC_NAME OMD_CC_ACC_NAME
#elif OMD_CC == OMD_CC_ACK
    #define OMD_CC_NAME OMD_CC_ACK_NAME
#elif OMD_CC == OMD_CC_APPLE_CLANG
    #define OMD_CC_NAME OMD_CC_APPLE_CLANG_NAME
#elif OMD_CC == OMD_CC_ARM
    #define OMD_CC_NAME OMD_CC_ARM_NAME
#elif OMD_CC == OMD_CC_AZTEC
    #define OMD_CC_NAME OMD_CC_AZTEC_NAME
#elif OMD_CC == OMD_CC_BORLAND
    #define OMD_CC_NAME OMD_CC_BORLAND_NAME
#elif OMD_CC == OMD_CC_CC65
    #define OMD_CC_NAME OMD_CC_CC65_NAME
#elif OMD_CC == OMD_CC_CLANG
    #define OMD_CC_NAME OMD_CC_CLANG_NAME
#elif OMD_CC == OMD_CC_COMEAU
    #define OMD_CC_NAME OMD_CC_COMEAU_NAME
#elif OMD_CC == OMD_CC_COMPAQ
    #define OMD_CC_NAME OMD_CC_COMPAQ_NAME
#elif OMD_CC == OMD_CC_COMPCERT
    #define OMD_CC_NAME OMD_CC_COMPCERT_NAME
#elif OMD_CC == OMD_CC_CONVEX
    #define OMD_CC_NAME OMD_CC_CONVEX_NAME
#elif OMD_CC == OMD_CC_CRAY
    #define OMD_CC_NAME OMD_CC_CRAY_NAME
#elif OMD_CC == OMD_CC_CWARRIOR
    #define OMD_CC_NAME OMD_CC_CWARRIOR_NAME
#elif OMD_CC == OMD_CC_DIAB
    #define OMD_CC_NAME OMD_CC_DIAB_NAME
#elif OMD_CC == OMD_CC_DICE
    #define OMD_CC_NAME OMD_CC_DICE_NAME
#elif OMD_CC == OMD_CC_DIGNUS
    #define OMD_CC_NAME OMD_CC_DIGNUS_NAME
#elif OMD_CC == OMD_CC_DJGPP
    #define OMD_CC_NAME OMD_CC_DJGPP_NAME
#elif OMD_CC == OMD_CC_DMC
    #define OMD_CC_NAME OMD_CC_DMC_NAME
#elif OMD_CC == OMD_CC_EDG
    #define OMD_CC_NAME OMD_CC_EDG_NAME
#elif OMD_CC == OMD_CC_EKOPATH
    #define OMD_CC_NAME OMD_CC_EKOPATH_NAME
#elif OMD_CC == OMD_CC_GCC
    #define OMD_CC_NAME OMD_CC_GCC_NAME
#elif OMD_CC == OMD_CC_GHS
    #define OMD_CC_NAME OMD_CC_GHS_NAME
#elif OMD_CC == OMD_CC_HIGHC
    #define OMD_CC_NAME OMD_CC_HIGHC_NAME
#elif OMD_CC == OMD_CC_HP_ACC
    #define OMD_CC_NAME OMD_CC_HP_ACC_NAME
#elif OMD_CC == OMD_CC_HP_ANSI
    #define OMD_CC_NAME OMD_CC_HP_ANSI_NAME
#elif OMD_CC == OMD_CC_IAR
    #define OMD_CC_NAME OMD_CC_IAR_NAME
#elif OMD_CC == OMD_CC_IBM_XL
    #define OMD_CC_NAME OMD_CC_IBM_XL_NAME
#elif OMD_CC == OMD_CC_IBMZ_XL
    #define OMD_CC_NAME OMD_CC_IBMZ_XL_NAME
#elif OMD_CC == OMD_CC_ICC
    #define OMD_CC_NAME OMD_CC_ICC_NAME
#elif OMD_CC == OMD_CC_IMAGECRAFT
    #define OMD_CC_NAME OMD_CC_IMAGECRAFT_NAME
#elif OMD_CC == OMD_CC_KCC
    #define OMD_CC_NAME OMD_CC_KCC_NAME
#elif OMD_CC == OMD_CC_KEIL_C166
    #define OMD_CC_NAME OMD_CC_KEIL_C166_NAME
#elif OMD_CC == OMD_CC_KEIL_C51
    #define OMD_CC_NAME OMD_CC_KEIL_C51_NAME
#elif OMD_CC == OMD_CC_KEIL_CARM
    #define OMD_CC_NAME OMD_CC_KEIL_CARM_NAME
#elif OMD_CC == OMD_CC_LCC
    #define OMD_CC_NAME OMD_CC_LCC_NAME
#elif OMD_CC == OMD_CC_LLVM
    #define OMD_CC_NAME OMD_CC_LLVM_NAME
#elif OMD_CC == OMD_CC_MCST
    #define OMD_CC_NAME OMD_CC_MCST_NAME
#elif OMD_CC == OMD_CC_MINGW
    #define OMD_CC_NAME OMD_CC_MINGW_NAME
#elif OMD_CC == OMD_CC_MINGW64
    #define OMD_CC_NAME OMD_CC_MINGW64_NAME
#elif OMD_CC == OMD_CC_MIPSPRO
    #define OMD_CC_NAME OMD_CC_MIPSPRO_NAME
#elif OMD_CC == OMD_CC_MPW
    #define OMD_CC_NAME OMD_CC_MPW_NAME
#elif OMD_CC == OMD_CC_MRI
    #define OMD_CC_NAME OMD_CC_MRI_NAME
#elif OMD_CC == OMD_CC_MSVC
    #define OMD_CC_NAME OMD_CC_MSVC_NAME
#elif OMD_CC == OMD_CC_NVCC
    #define OMD_CC_NAME OMD_CC_NVCC_NAME
#elif OMD_CC == OMD_CC_NWCC
    #define OMD_CC_NAME OMD_CC_NWCC_NAME
#elif OMD_CC == OMD_CC_OPEN64
    #define OMD_CC_NAME OMD_CC_OPEN64_NAME
#elif OMD_CC == OMD_CC_OPENSERVER
    #define OMD_CC_NAME OMD_CC_OPENSERVER_NAME
#elif OMD_CC == OMD_CC_ORANGE
    #define OMD_CC_NAME OMD_CC_ORANGE_NAME
#elif OMD_CC == OMD_CC_PALM
    #define OMD_CC_NAME OMD_CC_PALM_NAME
#elif OMD_CC == OMD_CC_PGI
    #define OMD_CC_NAME OMD_CC_PGI_NAME
#elif OMD_CC == OMD_CC_SDCC
    #define OMD_CC_NAME OMD_CC_SDCC_NAME
#elif OMD_CC == OMD_CC_SNC
    #define OMD_CC_NAME OMD_CC_SNC_NAME
#elif OMD_CC == OMD_CC_STRATUS_VOS
    #define OMD_CC_NAME OMD_CC_STRATUS_VOS_NAME
#elif OMD_CC == OMD_CC_SUNPRO
    #define OMD_CC_NAME OMD_CC_SUNPRO_NAME
#elif OMD_CC == OMD_CC_TCC
    #define OMD_CC_NAME OMD_CC_TCC_NAME
#elif OMD_CC == OMD_CC_TENDRA
    #define OMD_CC_NAME OMD_CC_TENDRA_NAME
#elif OMD_CC == OMD_CC_THINK
    #define OMD_CC_NAME OMD_CC_THINK_NAME
#elif OMD_CC == OMD_CC_TURBO
    #define OMD_CC_NAME OMD_CC_TURBO_NAME
#elif OMD_CC == OMD_CC_WATCOM
    #define OMD_CC_NAME OMD_CC_WATCOM_NAME
#elif OMD_CC == OMD_CC_Z88DK
    #define OMD_CC_NAME OMD_CC_Z88DK_NAME
#endif

/* Safeguard */
#if !defined(OMD_CC_NAME)
    #define OMD_CC_NAME OMD_CC_UNKNOWN_NAME
#endif
