#include <omdetect/internal/preamble.h>

#if OMD_STD_RAW_C_VERSION >= OMD_STD_C23
    #define OMD_STD_C_VERSION OMD_STD_C23
#elif OMD_STD_RAW_C_VERSION >= OMD_STD_C17
    #define OMD_STD_C_VERSION OMD_STD_C17
#elif OMD_STD_RAW_C_VERSION >= OMD_STD_C11
    #define OMD_STD_C_VERSION OMD_STD_C11
#elif OMD_STD_RAW_C_VERSION >= OMD_STD_C99
    #define OMD_STD_C_VERSION OMD_STD_C99
#elif OMD_STD_RAW_C_VERSION >= OMD_STD_C94
    #define OMD_STD_C_VERSION OMD_STD_C94
#elif OMD_STD_RAW_C_VERSION >= OMD_STD_C90
    #define OMD_STD_C_VERSION OMD_STD_C90
#elif OMD_STD_RAW_C_VERSION >= OMD_STD_C89
    #define OMD_STD_C_VERSION OMD_STD_C89
#endif
