#include <omdetect/internal/preamble.h>
#include <omdetect/version.h>

#if OMD_STD_RAW_CPP_VERSION >= OMD_STD_CPP23
    #define OMD_STD_CPP_VERSION OMD_STD_CPP23
#elif OMD_STD_RAW_CPP_VERSION >= OMD_STD_CPP20
    #define OMD_STD_CPP_VERSION OMD_STD_CPP20
#elif OMD_STD_RAW_CPP_VERSION >= OMD_STD_CPP17
    #define OMD_STD_CPP_VERSION OMD_STD_CPP17
#elif OMD_STD_RAW_CPP_VERSION >= OMD_STD_CPP14
    #define OMD_STD_CPP_VERSION OMD_STD_CPP14
#elif OMD_STD_RAW_CPP_VERSION >= OMD_STD_CPP11
    #define OMD_STD_CPP_VERSION OMD_STD_CPP11
#elif OMD_STD_RAW_CPP_VERSION >= OMD_STD_CPP98
    #define OMD_STD_CPP_VERSION OMD_STD_CPP98
#endif
