#include <omdetect/internal/preamble.h>

#if OMD_STD_RAW_POSIX_VERSION >= OMD_STD_POSIX_1_2008
    #define OMD_STD_POSIX_VERSION OMD_STD_POSIX_1_2008
#elif OMD_STD_RAW_POSIX_VERSION >= OMD_STD_POSIX_1_2001
    #define OMD_STD_POSIX_VERSION OMD_STD_POSIX_1_2001
#elif OMD_STD_RAW_POSIX_VERSION >= OMD_STD_POSIX_1C_1995
    #define OMD_STD_POSIX_VERSION OMD_STD_POSIX_1C_1995
#elif OMD_STD_RAW_POSIX_VERSION >= OMD_STD_POSIX_1B_1993
    #define OMD_STD_POSIX_VERSION OMD_STD_POSIX_1B_1993
#elif OMD_STD_RAW_POSIX_VERSION >= OMD_STD_POSIX_1_1990
    #define OMD_STD_POSIX_VERSION OMD_STD_POSIX_1_1990
#elif OMD_STD_RAW_POSIX_VERSION >= OMD_STD_POSIX_1_1988
    #define OMD_STD_POSIX_VERSION OMD_STD_POSIX_1_1988
#endif
