#include <omdetect/internal/preamble.h>
#include <omdetect/version.h>

#include <Availability.h>
#if !defined(__IPHONE_2_0)
    #include <AvailabilityVersions.h>
#endif

#if defined(__IPHONE_17_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(17, 2, 0)
#elif defined(__IPHONE_17_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(17, 1, 0)
#elif defined(__IPHONE_17_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(17, 0, 0)
#elif defined(__IPHONE_16_7)
    #define OMD_PLATFORM_VERSION OMD_VERSION(16, 7, 0)
#elif defined(__IPHONE_16_6)
    #define OMD_PLATFORM_VERSION OMD_VERSION(16, 6, 0)
#elif defined(__IPHONE_16_5)
    #define OMD_PLATFORM_VERSION OMD_VERSION(16, 5, 0)
#elif defined(__IPHONE_16_4)
    #define OMD_PLATFORM_VERSION OMD_VERSION(16, 4, 0)
#elif defined(__IPHONE_16_3)
    #define OMD_PLATFORM_VERSION OMD_VERSION(16, 3, 0)
#elif defined(__IPHONE_16_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(16, 2, 0)
#elif defined(__IPHONE_16_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(16, 1, 0)
#elif defined(__IPHONE_16_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(16, 0, 0)
#elif defined(__IPHONE_15_6)
    #define OMD_PLATFORM_VERSION OMD_VERSION(15, 6, 0)
#elif defined(__IPHONE_15_5)
    #define OMD_PLATFORM_VERSION OMD_VERSION(15, 5, 0)
#elif defined(__IPHONE_15_4)
    #define OMD_PLATFORM_VERSION OMD_VERSION(15, 4, 0)
#elif defined(__IPHONE_15_3)
    #define OMD_PLATFORM_VERSION OMD_VERSION(15, 3, 0)
#elif defined(__IPHONE_15_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(15, 2, 0)
#elif defined(__IPHONE_15_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(15, 1, 0)
#elif defined(__IPHONE_15_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(15, 0, 0)
#elif defined(__IPHONE_14_8)
    #define OMD_PLATFORM_VERSION OMD_VERSION(14, 8, 0)
#elif defined(__IPHONE_14_7)
    #define OMD_PLATFORM_VERSION OMD_VERSION(14, 7, 0)
#elif defined(__IPHONE_14_6)
    #define OMD_PLATFORM_VERSION OMD_VERSION(14, 6, 0)
#elif defined(__IPHONE_14_5)
    #define OMD_PLATFORM_VERSION OMD_VERSION(14, 5, 0)
#elif defined(__IPHONE_14_4)
    #define OMD_PLATFORM_VERSION OMD_VERSION(14, 4, 0)
#elif defined(__IPHONE_14_5)
    #define OMD_PLATFORM_VERSION OMD_VERSION(14, 5, 0)
#elif defined(__IPHONE_14_3)
    #define OMD_PLATFORM_VERSION OMD_VERSION(14, 3, 0)
#elif defined(__IPHONE_14_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(14, 2, 0)
#elif defined(__IPHONE_14_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(14, 1, 0)
#elif defined(__IPHONE_14_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(14, 0, 0)
#elif defined(__IPHONE_13_7)
    #define OMD_PLATFORM_VERSION OMD_VERSION(13, 7, 0)
#elif defined(__IPHONE_13_6)
    #define OMD_PLATFORM_VERSION OMD_VERSION(13, 6, 0)
#elif defined(__IPHONE_13_5)
    #define OMD_PLATFORM_VERSION OMD_VERSION(13, 5, 0)
#elif defined(__IPHONE_13_4)
    #define OMD_PLATFORM_VERSION OMD_VERSION(13, 4, 0)
#elif defined(__IPHONE_13_3)
    #define OMD_PLATFORM_VERSION OMD_VERSION(13, 3, 0)
#elif defined(__IPHONE_13_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(13, 2, 0)
#elif defined(__IPHONE_13_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(13, 1, 0)
#elif defined(__IPHONE_13_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(13, 0, 0)
#elif defined(__IPHONE_12_4)
    #define OMD_PLATFORM_VERSION OMD_VERSION(12, 4, 0)
#elif defined(__IPHONE_12_3)
    #define OMD_PLATFORM_VERSION OMD_VERSION(12, 3, 0)
#elif defined(__IPHONE_12_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(12, 2, 0)
#elif defined(__IPHONE_12_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(12, 1, 0)
#elif defined(__IPHONE_12_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(12, 0, 0)
#elif defined(__IPHONE_11_4)
    #define OMD_PLATFORM_VERSION OMD_VERSION(11, 4, 0)
#elif defined(__IPHONE_11_3)
    #define OMD_PLATFORM_VERSION OMD_VERSION(11, 3, 0)
#elif defined(__IPHONE_11_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(11, 2, 0)
#elif defined(__IPHONE_11_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(11, 1, 0)
#elif defined(__IPHONE_11_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(11, 0, 0)
#elif defined(__IPHONE_10_3)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 3, 0)
#elif defined(__IPHONE_10_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 2, 0)
#elif defined(__IPHONE_10_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 1, 0)
#elif defined(__IPHONE_10_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 0, 0)
#elif defined(__IPHONE_9_3)
    #define OMD_PLATFORM_VERSION OMD_VERSION(9, 3, 0)
#elif defined(__IPHONE_9_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(9, 2, 0)
#elif defined(__IPHONE_9_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(9, 1, 0)
#elif defined(__IPHONE_9_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(9, 0, 0)
#elif defined(__IPHONE_8_4)
    #define OMD_PLATFORM_VERSION OMD_VERSION(8, 4, 0)
#elif defined(__IPHONE_8_3)
    #define OMD_PLATFORM_VERSION OMD_VERSION(8, 3, 0)
#elif defined(__IPHONE_8_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(8, 2, 0)
#elif defined(__IPHONE_8_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(8, 1, 0)
#elif defined(__IPHONE_8_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(8, 0, 0)
#elif defined(__IPHONE_7_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(7, 1, 0)
#elif defined(__IPHONE_7_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(7, 0, 0)
#elif defined(__IPHONE_6_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(6, 1, 0)
#elif defined(__IPHONE_6_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(6, 0, 0)
#elif defined(__IPHONE_5_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(5, 1, 0)
#elif defined(__IPHONE_5_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(5, 0, 0)
#elif defined(__IPHONE_4_3)
    #define OMD_PLATFORM_VERSION OMD_VERSION(4, 3, 0)
#elif defined(__IPHONE_4_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(4, 2, 0)
#elif defined(__IPHONE_4_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(4, 1, 0)
#elif defined(__IPHONE_4_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(4, 0, 0)
#elif defined(__IPHONE_3_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(3, 2, 0)
#elif defined(__IPHONE_3_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(3, 1, 0)
#elif defined(__IPHONE_3_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(3, 0, 0)
#elif defined(__IPHONE_2_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(2, 2, 0)
#elif defined(__IPHONE_2_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(2, 1, 0)
#elif defined(__IPHONE_2_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(2, 0, 0)
#endif
