#include <omdetect/internal/preamble.h>
#include <omdetect/version.h>

#include <Availability.h>
#if !defined(__MAC_10_0)
    #include <AvailabilityVersions.h>
#endif

#if defined(__MAC_14_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(14, 2, 0)
#elif defined(__MAC_14_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(14, 1, 0)
#elif defined(__MAC_14_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(14, 0, 0)
#elif defined(__MAC_13_6)
    #define OMD_PLATFORM_VERSION OMD_VERSION(13, 6, 0)
#elif defined(__MAC_13_5)
    #define OMD_PLATFORM_VERSION OMD_VERSION(13, 5, 0)
#elif defined(__MAC_13_4)
    #define OMD_PLATFORM_VERSION OMD_VERSION(13, 4, 0)
#elif defined(__MAC_13_3)
    #define OMD_PLATFORM_VERSION OMD_VERSION(13, 3, 0)
#elif defined(__MAC_13_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(13, 2, 0)
#elif defined(__MAC_13_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(13, 1, 0)
#elif defined(__MAC_13_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(13, 1, 0)
#elif defined(__MAC_13_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(13, 0, 0)
#elif defined(__MAC_12_7)
    #define OMD_PLATFORM_VERSION OMD_VERSION(12, 7, 0)
#elif defined(__MAC_12_6)
    #define OMD_PLATFORM_VERSION OMD_VERSION(12, 6, 0)
#elif defined(__MAC_12_5)
    #define OMD_PLATFORM_VERSION OMD_VERSION(12, 5, 0)
#elif defined(__MAC_12_4)
    #define OMD_PLATFORM_VERSION OMD_VERSION(12, 4, 0)
#elif defined(__MAC_12_3)
    #define OMD_PLATFORM_VERSION OMD_VERSION(12, 3, 0)
#elif defined(__MAC_12_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(12, 2, 0)
#elif defined(__MAC_12_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(12, 1, 0)
#elif defined(__MAC_12_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(12, 0, 0)
#elif defined(__MAC_11_6)
    #define OMD_PLATFORM_VERSION OMD_VERSION(11, 6, 0)
#elif defined(__MAC_11_5)
    #define OMD_PLATFORM_VERSION OMD_VERSION(11, 5, 0)
#elif defined(__MAC_11_4)
    #define OMD_PLATFORM_VERSION OMD_VERSION(11, 4, 0)
#elif defined(__MAC_11_3)
    #define OMD_PLATFORM_VERSION OMD_VERSION(11, 3, 0)
#elif defined(__MAC_11_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(11, 1, 0)
#elif defined(__MAC_11_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(11, 0, 0)
#elif defined(__MAC_10_16)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 16, 0)
#elif defined(__MAC_10_15_4)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 15, 4)
#elif defined(__MAC_10_15_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 15, 1)
#elif defined(__MAC_10_15)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 15, 0)
#elif defined(__MAC_10_14_6)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 14, 6)
#elif defined(__MAC_10_14_5)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 14, 5)
#elif defined(__MAC_10_14_4)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 14, 4)
#elif defined(__MAC_10_14_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 14, 1)
#elif defined(__MAC_10_14)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 14, 0)
#elif defined(__MAC_10_13_4)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 13, 4)
#elif defined(__MAC_10_13_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 13, 2)
#elif defined(__MAC_10_13_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 13, 1)
#elif defined(__MAC_10_13)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 13, 0)
#elif defined(__MAC_10_12_4)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 12, 4)
#elif defined(__MAC_10_12_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 12, 2)
#elif defined(__MAC_10_12_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 12, 1)
#elif defined(__MAC_10_12)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 12, 0)
#elif defined(__MAC_10_11_4)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 11, 4)
#elif defined(__MAC_10_11_3)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 11, 3)
#elif defined(__MAC_10_11_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 11, 2)
#elif defined(__MAC_10_11)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 11, 0)
#elif defined(__MAC_10_10_3)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 10, 3)
#elif defined(__MAC_10_10_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 10, 2)
#elif defined(__MAC_10_10)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 10, 0)
#elif defined(__MAC_10_9)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 9, 0)
#elif defined(__MAC_10_8)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 8, 0)
#elif defined(__MAC_10_7)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 7, 0)
#elif defined(__MAC_10_6)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 6, 0)
#elif defined(__MAC_10_5)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 5, 0)
#elif defined(__MAC_10_4)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 4, 0)
#elif defined(__MAC_10_3)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 3, 0)
#elif defined(__MAC_10_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 2, 0)
#elif defined(__MAC_10_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 1, 0)
#elif defined(__MAC_10_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 0, 0)
#endif
