#include <omdetect/internal/preamble.h>
#include <omdetect/version.h>

#include <sys/param.h>

#if defined(OpenBSD7_4)
    #define OMD_PLATFORM_VERSION OMD_VERSION(7, 4, 0)
#elif defined(OpenBSD7_3)
    #define OMD_PLATFORM_VERSION OMD_VERSION(7, 3, 0)
#elif defined(OpenBSD7_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(7, 2, 0)
#elif defined(OpenBSD7_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(7, 1, 0)
#elif defined(OpenBSD7_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(7, 0, 0)
#elif defined(OpenBSD6_9)
    #define OMD_PLATFORM_VERSION OMD_VERSION(6, 9, 0)
#elif defined(OpenBSD6_8)
    #define OMD_PLATFORM_VERSION OMD_VERSION(6, 8, 0)
#elif defined(OpenBSD6_7)
    #define OMD_PLATFORM_VERSION OMD_VERSION(6, 7, 0)
#elif defined(OpenBSD6_6)
    #define OMD_PLATFORM_VERSION OMD_VERSION(6, 6, 0)
#elif defined(OpenBSD6_5)
    #define OMD_PLATFORM_VERSION OMD_VERSION(6, 5, 0)
#elif defined(OpenBSD6_4)
    #define OMD_PLATFORM_VERSION OMD_VERSION(6, 4, 0)
#elif defined(OpenBSD6_3)
    #define OMD_PLATFORM_VERSION OMD_VERSION(6, 3, 0)
#elif defined(OpenBSD6_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(6, 2, 0)
#elif defined(OpenBSD6_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(6, 1, 0)
#elif defined(OpenBSD6_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(6, 0, 0)
#elif defined(OpenBSD5_9)
    #define OMD_PLATFORM_VERSION OMD_VERSION(5, 9, 0)
#elif defined(OpenBSD5_8)
    #define OMD_PLATFORM_VERSION OMD_VERSION(5, 8, 0)
#elif defined(OpenBSD5_7)
    #define OMD_PLATFORM_VERSION OMD_VERSION(5, 7, 0)
#elif defined(OpenBSD5_6)
    #define OMD_PLATFORM_VERSION OMD_VERSION(5, 6, 0)
#elif defined(OpenBSD5_5)
    #define OMD_PLATFORM_VERSION OMD_VERSION(5, 5, 0)
#elif defined(OpenBSD5_4)
    #define OMD_PLATFORM_VERSION OMD_VERSION(5, 4, 0)
#elif defined(OpenBSD5_3)
    #define OMD_PLATFORM_VERSION OMD_VERSION(5, 3, 0)
#elif defined(OpenBSD5_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(5, 2, 0)
#elif defined(OpenBSD5_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(5, 1, 0)
#elif defined(OpenBSD5_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(5, 0, 0)
#elif defined(OpenBSD4_9)
    #define OMD_PLATFORM_VERSION OMD_VERSION(4, 9, 0)
#elif defined(OpenBSD4_8)
    #define OMD_PLATFORM_VERSION OMD_VERSION(4, 8, 0)
#elif defined(OpenBSD4_7)
    #define OMD_PLATFORM_VERSION OMD_VERSION(4, 7, 0)
#elif defined(OpenBSD4_6)
    #define OMD_PLATFORM_VERSION OMD_VERSION(4, 6, 0)
#elif defined(OpenBSD4_5)
    #define OMD_PLATFORM_VERSION OMD_VERSION(4, 5, 0)
#elif defined(OpenBSD4_4)
    #define OMD_PLATFORM_VERSION OMD_VERSION(4, 4, 0)
#elif defined(OpenBSD4_3)
    #define OMD_PLATFORM_VERSION OMD_VERSION(4, 3, 0)
#elif defined(OpenBSD4_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(4, 2, 0)
#elif defined(OpenBSD4_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(4, 1, 0)
#elif defined(OpenBSD4_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(4, 0, 0)
#elif defined(OpenBSD3_9)
    #define OMD_PLATFORM_VERSION OMD_VERSION(3, 9, 0)
#elif defined(OpenBSD3_8)
    #define OMD_PLATFORM_VERSION OMD_VERSION(3, 8, 0)
#elif defined(OpenBSD3_7)
    #define OMD_PLATFORM_VERSION OMD_VERSION(3, 7, 0)
#elif defined(OpenBSD3_6)
    #define OMD_PLATFORM_VERSION OMD_VERSION(3, 6, 0)
#elif defined(OpenBSD3_5)
    #define OMD_PLATFORM_VERSION OMD_VERSION(3, 5, 0)
#elif defined(OpenBSD3_4)
    #define OMD_PLATFORM_VERSION OMD_VERSION(3, 4, 0)
#elif defined(OpenBSD3_3)
    #define OMD_PLATFORM_VERSION OMD_VERSION(3, 3, 0)
#elif defined(OpenBSD3_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(3, 2, 0)
#elif defined(OpenBSD3_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(3, 1, 0)
#elif defined(OpenBSD3_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(3, 0, 0)
#elif defined(OpenBSD2_9)
    #define OMD_PLATFORM_VERSION OMD_VERSION(2, 9, 0)
#elif defined(OpenBSD2_8)
    #define OMD_PLATFORM_VERSION OMD_VERSION(2, 8, 0)
#elif defined(OpenBSD2_7)
    #define OMD_PLATFORM_VERSION OMD_VERSION(2, 7, 0)
#elif defined(OpenBSD2_6)
    #define OMD_PLATFORM_VERSION OMD_VERSION(2, 6, 0)
#elif defined(OpenBSD2_5)
    #define OMD_PLATFORM_VERSION OMD_VERSION(2, 5, 0)
#elif defined(OpenBSD2_4)
    #define OMD_PLATFORM_VERSION OMD_VERSION(2, 4, 0)
#elif defined(OpenBSD2_3)
    #define OMD_PLATFORM_VERSION OMD_VERSION(2, 3, 0)
#elif defined(OpenBSD2_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(2, 2, 0)
#elif defined(OpenBSD2_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(2, 1, 0)
#elif defined(OpenBSD2_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(2, 0, 0)
#elif defined(OpenBSD1_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(1, 2, 0)
#elif defined(OpenBSD1_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(1, 1, 0)
#endif
