#include <omdetect/internal/preamble.h>
#include <omdetect/version.h>

#if defined(__SunOS_5_11)
    #define OMD_PLATFORM_VERSION OMD_VERSION(11, 0, 0)
#elif defined(__SunOS_5_10)
    #define OMD_PLATFORM_VERSION OMD_VERSION(10, 0, 0)
#elif defined(__SunOS_5_9)
    #define OMD_PLATFORM_VERSION OMD_VERSION(9, 0, 0)
#elif defined(__SunOS_5_8)
    #define OMD_PLATFORM_VERSION OMD_VERSION(8, 0, 0)
#elif defined(__SunOS_5_7)
    #define OMD_PLATFORM_VERSION OMD_VERSION(7, 0, 0)
#elif defined(__SunOS_5_6)
    #define OMD_PLATFORM_VERSION OMD_VERSION(2, 6, 0)
#elif defined(__SunOS_5_5_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(2, 5, 1)
#elif defined(__SunOS_5_5)
    #define OMD_PLATFORM_VERSION OMD_VERSION(2, 5, 0)
#elif defined(__SunOS_5_4)
    #define OMD_PLATFORM_VERSION OMD_VERSION(2, 4, 0)
#elif defined(__SunOS_5_3)
    #define OMD_PLATFORM_VERSION OMD_VERSION(2, 3, 0)
#elif defined(__SunOS_5_2)
    #define OMD_PLATFORM_VERSION OMD_VERSION(2, 2, 0)
#elif defined(__SunOS_5_1)
    #define OMD_PLATFORM_VERSION OMD_VERSION(2, 1, 0)
#elif defined(__SunOS_5_0)
    #define OMD_PLATFORM_VERSION OMD_VERSION(2, 0, 0)
#endif
